-- BotZone secure catalog and administrator access.
-- Run this migration with the Supabase CLI or paste it into the Supabase SQL editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 2 and 100),
  subtitle text not null default '' check (char_length(subtitle) <= 240),
  type text not null check (type in ('bot', 'item')),
  category text not null check (char_length(category) between 2 and 80),
  price bigint not null check (price >= 0),
  old_price bigint check (old_price is null or old_price >= price),
  badge text check (badge is null or char_length(badge) <= 30),
  tone text not null default 'violet' check (tone in ('violet', 'blue', 'orange', 'pink', 'green', 'cyan')),
  rating numeric(2,1) not null default 5.0 check (rating between 0 and 5),
  reviews integer not null default 0 check (reviews >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.products enable row level security;

-- Administrators can verify only their own membership. No browser user can add
-- themselves to this table; promotion is performed from the SQL editor only.
drop policy if exists "admins can read own membership" on public.admin_users;
create policy "admins can read own membership"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

-- Visitors can read only products explicitly marked active.
drop policy if exists "public can read active products" on public.products;
create policy "public can read active products"
on public.products for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products"
on public.products for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products"
on public.products for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products"
on public.products for delete
to authenticated
using (public.is_admin());

-- The catalog intentionally starts empty. Create an Auth user in the Supabase
-- dashboard, then promote that user's UUID privately in the SQL editor:
-- insert into public.admin_users (user_id) values ('YOUR_AUTH_USER_UUID');
